NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),  # делаем так, чтобы все
    # адреса из нашего приложения (simpleapp/urls.py) сами
    # автоматически подключались когда мы их добавим
    path('', include('protect.urls')),  # перенаправление корневой
    # страницы в приложение protect
    path('sign/', include('sign.urls')),  # URL которых начинается
    # с sign/, перенаправляем в приложение sign
    path('accounts/', include('allauth.urls')),
]

NewsPaper/news/urls.py
from django.urls import path
from .views import News, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, Search, \
    CategoryListView, subscribe_to_category, unsubscribe_from_category, CategoryDetailView
from django.views.decorators.cache import cache_page

# from .views import index

app_name = 'news'
urlpatterns = [
    # path('', cache_page(60 * 1)(News.as_view())),
    path('', News.as_view()),
    # path('', index, name='index'),
    # path('<int:pk>/', cache_page(60 * 5)(PostDetailView.as_view()), name='post_detail'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='post_edit'),
    path('search/', Search.as_view(), name='search'),
    path('login/', PostUpdateView.as_view(template_name='users/login.html'), name='login'),
    path('category/<int:pk>', CategoryListView.as_view(), name='category'),
    path('cat_detail/<int:pk>', CategoryDetailView.as_view(), name='cat_detail'),
    path('subscribe/<int:pk>', subscribe_to_category, name='subscribe'),
    path('unsubscribe/<int:pk>/', unsubscribe_from_category, name='unsubscribe'),
]

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.core.validators import MinValueValidator

from django.core.cache import cache
from django.urls import reverse


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        otherRat = Comment.objects.filter(commentRat_id=self.id).aggregate(Sum('rating')).get('rating__sum')

        oRat = 0
        oRat += otherRat.get('rating')

        self.ratingAuthor = pRat * 3 + cRat + oRat
        self.save()

    def __str__(self):
        return f'{self.authorUser.username}'

class CategorySubscriber(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    subscriber = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.subscriber}:  {self.category.name}'


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, through='CategorySubscriber', blank=True)

    def get_category(self):
        return self.name
    def __str__(self):
        return f'{self.name}'

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name='Автор')

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE, verbose_name='Новость/статья')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    postCategory = models.ManyToManyField(Category, through='PostCategory', verbose_name='Тематика')
    title = models.CharField(max_length=128, verbose_name='Заголовок')
    text = models.TextField(verbose_name='Текст')
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def get_absolute_url(self):
        return f'/news/{self.id}'
        # return reverse('post', kwargs={'post_id': self.pk})

    def __str__(self):
        return f'{self.title}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем
        # метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}')  # затем удаляем
        # его из кэша, чтобы сбросить его


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.categoryThrough.id}'

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return reverse('post', kwargs={'post_id': self.pk})
        # return f'/news/{self.id}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'{self.authorUser.username}'

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper/news/forms.py
from django import forms
from django.forms import ModelForm, BooleanField, Textarea  # Импортируем true-false поле
from django_filters import ModelChoiceFilter

from .models import Post, PostCategory, Category


# Создаём модельную форму
class PostForm(ModelForm):
    check_box = BooleanField(label='Галочка!')  # добавляем галочку или же true-false поле

    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['author.authorUser|title'].empty_label = "Автор не выбран"
        self.fields[''].empty_label = "Не выбрано"
    # в класс мета, как обычно, надо написать модель, по которой будет строиться форма и нужные нам поля.
    # Мы уже делали что-то похожее с фильтрами.


    class Meta:
        model = Post
        fields = ['author', 'title', 'text', 'categoryType', 'postCategory', 'check_box']
        widgets = {
            'text': forms.Textarea(attrs={'cols': 50, 'rows': 2}),
        }

NewsPaper/news/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.core.paginator import Paginator
from .models import Post, Category
from .filters import PostFilter
from .forms import PostForm
from django.urls import resolve

from django.http.response import HttpResponse, HttpResponseRedirect
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.core.cache import cache

# from NewsPaper.settings import DEFAULT_FROM_EMAIL
from django.conf import settings

DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL


class News(ListView):
    model = Post
    template_name = 'news.html'
    context_object_name = 'news'
    ordering = ['-dateCreation']
    form_class = PostForm
    paginate_by = 8  # постраничный вывод в 1элемент

    def get_queryset(self):
        queryset = PostFilter(self.request.GET, super().get_queryset()).qs
        # фильтрация queryset-ом
        return queryset

    def get_context_data(self, **kwargs):  # забираем отфильтрованные
        # объекты переопределяя метод get_context_data у
        # наследуемого класса - полиморфизм
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET,
                                       queryset=self.get_queryset())  # вписываем наш фильтр в контекст
        context['time_now'] = datetime.utcnow()  # добавим переменную текущей даты time_now
        # context['form'] = PostForm()
        return context

    # def post(self, request, *args, **kwargs):
    #     # берём значения для нового товара из POST-запроса отправленного на сервер
    #     form = self.form_class(request.POST)
    #
    #     if form.is_valid():
    #         form.save()
    #     return super().get(request, *args, **kwargs)


# создаём представление, в котором будут детали конкретного отдельного товара
class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post  # модель всё та же, но мы хотим получать детали конкретно отдельного товара
    template_name = 'news/post_detail.html'  # название шаблона будет product.html
    queryset = Post.objects.all()
    context_object_name = 'post'  # название объекта

    def post_list_view(request):
        paginator = Paginator(News.objects.all(), per_page=7)
        page = paginator.page(request.GET.get('page', 2))
        return render(request, 'news/news.html', {
            'object_list': page.object_list,
            'page_obj': page,
        })

    def get_object(self, *args, **kwargs):  # переопределим метод получения объекта
        obj = cache.get(f'post-{self.kwargs["pk"]}', None)
        # кэш очень похож на словарь, и метод get действует
        # также. Он забирает значение по ключу - если его
        # нет, то забирает None.

        # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["pk"]}', obj)

        return obj


#  ++ дженерик для создания объекта. Надо указать только имя шаблона и класс формы
#  который мы написали в прошлом юните. Остальное он сделает за вас
class PostCreateView(PermissionRequiredMixin, CreateView):
    model = Post
    template_name = 'news/post_create.html'
    form_class = PostForm
    context_object_name = 'news'
    permission_required = ('news.add_post',)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        user = request.user
        if form.is_valid():
            post = form.save(commit=False)
            # post.authorUser = Author.objects.get_or_create(user=user)[0]
            return self.form_valid(form)
        return redirect('news')


# дженерик для редактирования объекта
class PostUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'news/post_edit.html'
    form_class = PostForm
    context_object_name = 'news'
    permission_required = ('news.change_post',)

    # метод get_object вместо queryset для получения инфо об obj редактирования
    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


# дженерик для удаления товара
class PostDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'news/post_delete.html'
    queryset = Post.objects.all()
    success_url = '/news'
    permission_required = ('news.delete_post',)

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class Search(ListView):  # дженерик для поиска поста
    model = Post
    template_name = 'news/search.html'
    context_object_name = 'news'  # это имя списка, в котором будут лежать все объекты,
    # его надо указать, чтобы обратиться к самому списку объектов через HTML-шаблон
    ordering = ['-dateCreation']  # сортировка по дате публикации, сначала более новые  или
        # queryset = Post.objects.order_by('-dateCreation')
    paginate_by = 8

    def get_queryset(self):
        queryset = PostFilter(self.request.GET, super().get_queryset()).qs  # фильтрация queryset-ом
        return queryset

    def get_context_data(self, **kwargs):
        # забираем отфильтрованные объекты переопределяя метод get_context_data у
        # наследуемого класса (привет, полиморфизм, мы скучали!!!)
        context = super().get_context_data(**kwargs)
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
        # вписываем наш фильтр в контекст
        context['form'] = PostForm()
        return context


class CategoryListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'news/cat.html'
    context_object_name = 'news'  # коллекция записей из БД
    ordering = ['-dateCreation']
    paginate_by = 3

    def get_queryset(self):
        self.id = resolve(self.request.path_info).kwargs['pk']
        c = Category.objects.get(id=self.id)
        queryset = Post.objects.filter(postCategory=c)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        category = Category.objects.get(id=self.id)
        context['cat'] = Category.objects.get(pk=self.kwargs['pk'])
        context['subscribers'] = category.subscribers.all()
        subscribed = category.subscribers.filter(email=user.email)
        # if not subscribed:
        #     context['sub'] = True
        # else:
        #     context['sub'] = False
        context['category'] = category
        return context


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'news/cat_detail.html'
    queryset = Category.objects.all()
    context_object_name = 'categorys'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context_object_name = 'category'
        user = self.request.user
        cat = Category.objects.values('name')
        context['category_list'] = Category.objects.get(pk=self.kwargs['pk'])

    def show_category(request, category_id):
        return HttpResponse(f"Отображение категории с id = {category_id}")


@login_required
def subscribe_to_category(request, pk):
    category = Category.objects.get(pk=pk)
    category.subscribers.add(request.user.id)
    return redirect(request.META.get('HTTP_REFERER'))  # возвращает на страницу, с кот-й поступил запрос


@login_required
def unsubscribe_from_category(request, pk):  # отписаться от категории
    category = Category.objects.get(pk=pk)
    category.subscribers.remove(request.user.id)
    return redirect(request.META.get('HTTP_REFERER'))

NewsPaper/templates/news/cat.html
{% block content %} 

{% if user not in subscribers %}
<div>
    <em>
        Подписаться на категорию 
        <strong> {{ cat.name }} ? </strong>
    </em>
    <button>
        <a href = "{% url 'news:subscribe' cat.id %}" > Подписаться !</a>
    </button>
</div>
{% else %}
<div>
    <em>
        Отписаться от категории 
        <strong> {{ cat.name }} ? </strong>
    </em>
    <button>
        <a href = "{% url 'news:unsubscribe' cat.id %}">Отписаться!</a>
    </button>
</div>
{% endif %}

{% include 'news/posts.html' %}
{% endblock content %}

NewsPaper/templates/news/cat_detail.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %} News - Category list
{% endblock %}

{% block content %}
    <h1>Category List</h1>

    {% if categorys %}
    {% for category in categorys %}
    {{ category }}
    {% for post in category.all %}
        {{ post.text|censor:"'" }}
    {{ post }}
    {% endfor %}
    {% endfor %}


    {% else %}
    <p>There are no category </p>
    {% endif %}
<!--    <a href="{{ cat.get_absolute_url }}">{{ cat.name }}{{ post.author}} </a>-->


    <a href="/news/"> Все статьи </a>

{% endblock %}

NewsPaper/templates/news/cat_subscription.html
{% extends 'flatpages/default.html' %}

{% block title %}
    Subscription
{% endblock title %}

{% block content %}
    <h1>Здравствуйте {{ request.user.username }}!</h1>
    <h2>Вы выбрали категорию "{{ category.name }}" </h2>
    <hr>
    {% if is_not_subscribe %}
    <h4> Если вы хотите получать сообщения и всегда быть в курсе появления новых публикаций в данной категории, нажмите кнопку "Подписаться" </h4>
    <button><a href="subscribe_to_category/?pk={{ category.id }}">Подписаться</a></button>
    {% else %}
    <h4>Вы уже подписаны на эту категорию.</h4>
    <h4>Если больше не хотите получать уведомление о новых публикациях, нажмите на кнопку "Отписаться".</h4>
    <button><a href="unsubscribe_from_category/?pk={{ category.id }}">Отписаться</a></button>
    {% endif %}
{% endblock %}

NewsPaper/templates/news/category.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% block title %} Category {% endblock %}

{% block content %}

<div class="subscribe">
{% if category.id %}

    {% comment %}

    <em>Subscribe to {{ category.id }}?</em>
    <button><a href="{% url 'news:subscribe' category.id %}" class="button button-outline">Подписаться</a></button>

    {% endcomment %}

    <h3>Подписаться на категорию <strong>{{ category.name }}?</strong></h3>
    <h4><button> <a href="{% url 'subscribe' category.id %}"> Подписаться </a></button></h4>

{% endif %}
    <br>
    <a href="{% url 'categories' $}">Отобразить все каты !! </a>

</div>

{% include 'news/posts.html' %}  # категорию передают через инклюду

<br>
<br>
<h4><a href="/news/"> Вернуться к новостям </a></h4>

{% endblock content %}

NewsPaper/templates/news/details.html
{% load custom_filters %}

<h3>
  <a href="{% url 'details' %}">
    {{ post.title|censor:"'" }}
  </a>
</h3>

<p class="details">
    By <span class="author">{{ post.author }}</span>
    on <span class="date">{{ post.dateCreation }}</span>
    Category:
    {% for c in post.category.all %}
    <a href="{% url 'news:category' c.id %}" class="category">{{ c.name }}</a>
    {% endfor %}
</p>

NewsPaper/templates/news/pagination.html
{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a href="?page=1">Первая</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    <!-- Если есть следующая страница, то даём ссылку на неё и на самую последнюю страницу -->
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
    {% endif %}
{% endif %}

NewsPaper/templates/news/post_create.html
{% extends 'flatpages/default.html' %}
{% load static %}
{% load custom_filters %}

{% block title %} edit {% endblock %}

{% block content %}

<h3>Добавление публикации</h3>

<!--Дата публикации: {{ post.dateCreated|date:'d-m-Y H:i' }}-->

<!-- Форма для добавления -->
<form method="POST" name="edit">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Добавить статью">
</form>
<a href="/news/">Назад ко всем статьям</a>  <br>

{% endblock %}

NewsPaper/templates/news/post_delete.html
{% extends 'flatpages/default.html' %}
 
{% block title %} Product list {% endblock title %}
 
{% block content %}
<h2>Вы действительно хотите удалить данный пост?</h2>
<table>
    <thead>
        <th>Автор</th>
        <th>Заголовок</th>
        <th>дата публикации</th>
        <th>Текст</th>
    </thead>
    <tr>
        <td>{{ post.author.authorUser|title }}</td>
        <td>{{ post.title }}</td>
        <td>{{ post.dateCreation }}</td>
        <td>{{ post.text }}</td>
    </tr>
</table>
<br>
<br>
 
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="подтвердить"></form>
    <br>
    <a href="/news/"> Все статьи </a>
{% endblock content %}

NewsPaper/templates/news/post_detail.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %} Post list = news {% endblock title %}
 
{% block content %}
<table>
    <thead>
        <th>Автор публикации</th>
        <th>Заголовок</th>
        <th>Опубликовано</th>
        <th>Текст</th>
        <th>Категория</th>
    </thead>
    <tr>
        <td>{{ post.author.authorUser|title }}</td>
        <td>{{ post.title }}</td>
        <td>{{ post.dateCreation|date:'d M Y H:i' }}</td>
        <td>{{ post.text|censor:"'" }}</td>
        <td>
            {% for c in post.postCategory.values %}
            <a href="{% url 'news:category' c.id %}">{{c.name}}</a>
            {% endfor %}
        </td>

    </tr>
</table>
{% comment %}
{% if is_not_subscribe %}
<!--GET запрос передает в наше представление значение категории, переменная post.category.id, -->
<!--которая в дальнейшем необходима для добавления подписчиков-->
<button><a href="subscribe/?pk={{ news.PostCategory.id }}">Подписаться</a></button>
{% endif %}
{% endcomment %}

<a href="/news/"> Все статьи </a>

{% endblock content %}

NewsPaper/templates/news/post_edit.html
{% extends 'flatpages/default.html' %}
{% load static %}
{% load custom_filters %}

{% block title %} edit {% endblock %}

{% block content %}

<h3>Редактирование публикации</h3>

<!--Дата публикации: {{ post.dateCreated|date:'d-m-Y H:i' }}-->

<!-- Форма для добавления -->
<form method="POST" name="edit">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Добавить статью">
</form>
<a href="/news/">Назад ко всем статьям</a>  <br>

{% endblock %}

NewsPaper/templates/news/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% include 'flatpages/head_title.html' %}

{% block content %}

{% if news %}
<h3> Статьи рубрики {{ cat.name }}</h3>
{% for post in news %}

{#% include 'news/details.html' %#}

<p>
<h5><em>{{ post.title|censor:"'" }} </em> <br>
  {{ post.text|censor:"'" }} <br>
  *** *** </h5></p>
{% endfor %}

{% else %}
<h2> No News yet </h2>
{% endif %}

{% for c in category_list %}
{{ c.name }}

{#% include 'news/inc/buttons.html' %#}

{% endfor %}

<a href="/news/"> Все статьи </a><br>

<!--<a href="{% url 'news:cat_detail' cat.id  %}"> Рубрики </a> <br>-->

<!--{% include 'news/pagination.html' %}-->
{% endblock content %}

NewsPaper/templates/news/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %} News {% endblock title %}

{% block content %}

<h3>Поиск</h3>

<h4>Найдено статей {{ filter.qs|length }} из {{ page_obj.paginator.count }}</h4>

<!--<h5>Сегодня: {{ time_now|date:'d M Y' }}</h5>-->


<!-- Перед таблицей добавим форму для поиска -->
<form method="GET">
    {{ filter.form }} <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самому -->
    <input type="submit" value="Найти">
</form>

<a href="/news/"> Отобразить все статьи </a> <br>

<table>
    <thead>
        <th>Заголовок</th>
        <th>Автор</th>
        <th>Дата публикации</th>
        <th>Превью</th>
    </thead>
    {% for post in news %}
    <tr>
        <td><a href="{% url 'news:post_detail' post.id %}">{{ post.title|censor:"'" }}</a> <!-- перекинет на страницу новости -->
            <a href="{% url 'news:post_edit' post.id %}"><u>Редактировать</u></a>
            <a href="{% url 'news:post_delete' post.id %}"><u>Удалить</u></a>
        </td>
        <td>{{ post.author.authorUser|title }}</td>
        <td>{{ post.dateCreation|date:'d M Y' }}</td>
        <td>{{ post.text|censor:"'"|truncatechars:50 }}</td>
    </tr>
    {% endfor %}
</table>

<p><a href="{% url 'news:post_create' %}">Добавить статью</a></p> <br>

{% if is_paginated %}

    {% if page_obj.has_previous %}
        <a href="?page=1">Первая</a>
        <a href="?page={{ page_obj.previous_page_number }}"><<<</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a>{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">>>></a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Последняя</a>
    {% endif %}
{% endif %}

{% endblock %}