NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('news.urls')),  # делаем так, чтобы все
    # адреса из нашего приложения (simpleapp/urls.py) сами
    # автоматически подключались когда мы их добавим
    path('', include('protect.urls')),  # перенаправление корневой
    # страницы в приложение protect
    path('sign/', include('sign.urls')),  # URL которых начинается
    # с sign/, перенаправляем в приложение sign
    path('accounts/', include('allauth.urls')),
]

NewsPaper/news/urls.py
from django.urls import path
from .views import News, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, Search, \
    CategoryListView, subscribe_to_category, unsubscribe_from_category, CategoryDetailView
from django.views.decorators.cache import cache_page

# from .views import index

app_name = 'news'
urlpatterns = [
    # path('', cache_page(60 * 1)(News.as_view())),
    path('', News.as_view()),
    # path('', index, name='index'),
    # path('<int:pk>/', cache_page(60 * 5)(PostDetailView.as_view()), name='post_detail'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreateView.as_view(), name='post_create'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='post_delete'),
    path('edit/<int:pk>/', PostUpdateView.as_view(), name='post_edit'),
    path('search/', Search.as_view(), name='search'),
    path('login/', PostUpdateView.as_view(template_name='users/login.html'), name='login'),
    path('category/<int:pk>', CategoryListView.as_view(), name='category'),
    path('cat_detail/<int:pk>', CategoryDetailView.as_view(), name='cat_detail'),
    path('subscribe/<int:pk>', subscribe_to_category, name='subscribe'),
    path('unsubscribe/<int:pk>/', unsubscribe_from_category, name='unsubscribe'),
]

NewsPaper/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView
from .views import upgrade_me


app_name = 'sign'
urlpatterns = [
    path('login/',
         LoginView.as_view(template_name='sign/login.html'),
         name='login'),
    path('logout/',
         LogoutView.as_view(template_name='sign/logout.html'),
         name='logout'),
    path('signup/',
         BaseRegisterView.as_view(template_name='sign/signup.html'),
         name='signup'),
    path('upgrade/', upgrade_me, name='upgrade')
]

NewsPaper/templates/users/index.html
{% extends "main.html" %}

{% block content %}
<div class="container"></div>
    <h2>Страница авторизованного пользователя {#{request.user.username}#} </h2>
<!--    <div> Здесь может содержаться персональная информация для каждого пользователя-->
    </div>
    <div> <h3>{{request.user.username}},
        Вы подписаны на следующие рубрики: </h3>
        <ul>
           {% for category in categories %}
            <li>
                {{ category.get.category }}
                <a href="{% url 'news:unsubscribe' cat.id %}">
                    <button class="button-xsmall pure-button button-warning">
                        <i class="bi bi-bookmark-plus"></i>
                        Unsubscribe
                    </button>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="row">
    {% if is_not_author %}
    <div class="column">
        <form method="post" action="{% url 'sign:upgrade' %}">
            {% csrf_token %}
            <button type="submit" class="button"> Make me an Author </button>
        </form>
    </div>
    {% endif %}
    <div class="column">
        <a href="{% url 'sign:logout' %}" class="button-outline">Logout<br>
        </a><br>

    </div>
</div>
    <button> <a href="news/"> Перейти к статьям </a></button>

{% endblock %}

NewsPaper/templates/users/login.html
{% extends "templates/default.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Вход</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Войти</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Нужен аккаунт? <a class="ml-2" href="{% url 'register' %}">Регистрация</a>
            </small>
        </div>
    </div>
{% endblock content %}

NewsPaper/templates/users/logout.html
{% extends "flatpages/default.html" %}
{% block content %}
    <h2>Вы вышли из своей учетной записи</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Войти</a>
        </small>
    </div>
{% endblock content %}

NewsPaper/templates/users/profile.html
{% extends "main.html" %}

{% block content %}
<div class="container">
    <h2>Страница авторизованного пользователя {{request.user.username}}</h2>
    <div> Здесь может содержаться персональная информация для каждого пользователя

    </div>

    <div>You have successfully subscribed to:
        <ul>
           {% for category in categories %}
            <li>
                {{ category.get.category }}
                <a href="{% url 'news:unsubscribe' category.id %}">
                    <button class="button-xsmall pure-button button-warning">
                        <i class="bi bi-bookmark-plus"></i>
                        Unsubscribe
                    </button>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="row">
        {% if is_not_author %}
        <div class="column">
            <form method="post" action="{% url 'users:upgrade' %}">
                {% csrf_token %}
                <button type="submit" class="button"> Make me an Author </button>
            </form>
        </div>
        {% endif %}
        <div class="column">
            <a href="{% url 'users:logout' %}" class="button-outline">Logout
            </a>
        </div>
    </div>

    <button> <a href="news/"> Перейти к статьям </a></button>
</div>
<!--<button> <a href="sign:upgrade/"> Хочу быть Автором!</a> </button> <br>-->

<!--<button> <a href="sign:logout/">Выйти</a> </button>-->
{% endblock %}